### ISSUE TITLE
Support Prisma Select, Include and OrderBy 

### ISSUE THREAD

**Issue by fortezhuo** [m1212e/prismabox#18]
Any workaround for support generate typesafe for prisma select, include and orderBy with relation ?

**Comment by m1212e** [comment]
No currently this is not supported by prismabox since I actually never used that myself but I guess that would make sense to implement. Would you be interested in opening a PR? I could take some time throughout the next weeks to tackle this. Let me know if you'd be interested!

**Comment by fortezhuo** [comment]
Yes. I have opened a PR. please review : https://github.com/m1212e/prismabox/pull/19

**Comment by fortezhuo** [comment]
Closed. Already implemented 1.1.14
