### ISSUE TITLE
Partial Recursive not working

### ISSUE THREAD

**Issue by fortezhuo** [m1212e/prismabox#22]
Hi,

I have found this issue today when I am using allow Recursion

```
export const CategoryWhere = Type.Partial(
  Type.Recursive(
    (Self) =>
      Type.Object({
        AND: Type.Union([Self, Type.Array(Self)]),
        NOT: Type.Union([Self, Type.Array(Self)]),
        OR: Type.Array(Self),
        id: Type.Integer(),
        name: Type.String(),
      }),
    { $id: "Category" },
  ),
  { additionalProperties: false },
);
```
This schema can't be decoded / parsed using Value.Decode / Value.Parse

```
TypeDereferenceError: Unable to dereference schema with $id 'undefined'
```

Just filing this issue and linked with typebox's discussion https://github.com/sinclairzx81/typebox/discussions/1001

**Comment by m1212e** [comment]
Hey, I think this issue is more related to typebox, am I right?

**Comment by fortezhuo** [comment]
Yea. Just open this issue for linking to the typebox discussion 🙏

**Comment by m1212e** [comment]
I see, thanks for the info! I'll close this for now. If you have updates on this which might indicate an error in prismabox, feel free to re-open!
