### ISSUE TITLE
Support MongoDB composite types

### ISSUE THREAD

**Issue by shahriar-shojib** [m1212e/prismabox#23]
I would like to use this in my project but unfortunately, I depend on MongoDB composite types a lot.
Please Consider adding support to it

**Comment by m1212e** [comment]
Hi, thanks for your issue. I'll look into it throughout the next weeks but cannot promise anything since I don't have much time currently. If you need that feature urgently, please consider opening a PR!

**Comment by Zubaer123456** [comment]
Hello my bKash marchent account dashbord password change the another people please help me

**Comment by m1212e** [comment]
@Zubaer123456 please refrain from hijacking other issues. If you think you issue is somehow related to prismabox, please open a new one.

**Comment by m1212e** [comment]
Since I currently don't need this feature myself and do not have the time to implement it I'll close this for now. Feel free to contact me here again/reopen to discuss a PR!
