### ISSUE TITLE
Add support for Transform types

### ISSUE THREAD

**Issue by anotheri** [m1212e/prismabox#25]
First of all thanks for maintaining this lib! 

I have a **feature request**. The Typebox supports types transformations now:

https://github.com/sinclairzx81/typebox?tab=readme-ov-file#transform-types

It seems an alternative approach for what `useJsonTypes` flag allows to have.
There is an idea on how that can be done. So for example in scope of Dates, it can be something like this:

```typescript
// Define custom type with transformation, this assumes format date-time has been registered
const IsoDate = (options?: StringOptions) =>
  Type.Transform(Type.String({ format: 'date-time', ...options }))
    .Decode(value => new Date(value))
    .Encode(value => value.toISOString())

// Generated schema consuming the type helper
MySchema = Type.Object({
  createdAt: IsoDate()
});
```

So it can be realized the next way:
1) add config option with path to file with custom types (this module(s) should be imported into generated schema files if one of custom types are used in schema);
2) maybe add some predefined custom types, e.g. this IsoDate which is quite generic and useful;
3) add a new annotation which would apply custom type to the particular field in generated schema, e.g.:

```prisma
/// @prismabox.type{ custom: 'IsoDate' }
```

So in case when generated schemas are used as DTO (i guess this is one of the main reasons to generate Typebox schemas from Prisma models), the application codebase most probably should rely on `StaticDecode<typeof T>` — kind of "internal" type, and both original `Static<typeof T>` and `StaticEncode<typeof T>` supposed to be equal and represent "external" JSON schema valid type, which can easily be used for example with Fastify, Open API documentation, etc.

On side note, if you prefer to have a couple hardcoded custom types in combination with `useJsonTypes` flag, here is  an "inverted" helper respectively:

```typescript
const IsoString = (options?: DateOptions) =>
  Type.Transform(Type.Date({ ...options }))
    .Decode((value) => value.toISOString())
    .Encode((value) => new Date(value));
```

Please let me know what do you think.

**Comment by m1212e** [comment]
Didn't know about this feature yet but this seems like a good way to flawlessly support pure JSON schema while maintaining prisma compatibility which expects native date objects. Sounds like a good idea. Currently I'm sick and pretty busy but I'll have a look throughout the next weeks. Feel free to open a PR or ask any questions if you'd like to tackle this yourself! Thanks for the notice!

**Comment by m1212e** [comment]
Hey @anotheri I just released this dev version of prismabox: https://www.npmjs.com/package/prismabox/v/1.1.16-dev.0
Your suggestion was very helpful! Could you please test this for correctness and compatibility with previous versions so I know if it's breaking backwards compatibility? Thank you very much!

**Comment by anotheri** [comment]
@m1212e nice! that was fast 🚀 I'll take a look today.

FYI I started yesterday with PR, but it took a bit of time to figure out with local setup (bun + biome, which i didn't use before). Also i've noticed that there are no tests, which makes it a bit harder to make sure that contribution has no breaking changes.

So you may consider also a couple DX improvements for community/contributors:
- basic guide how to contribute into project (including local dev setup);
- and add some automated test as you can see would also be nice :) (nevertheless i'll check backwards compatibility now)

**Comment by anotheri** [comment]
@m1212e at quick glance it works exactly as I expected! 👍  I didn't notice any breaking changes in my codebase (although it is in a quite WIP state).

**Comment by m1212e** [comment]
Nice, great to hear that!
Regarding the two things you stated: You are so very right! If you'd like to contribute that I'd be more than happy to review a PR :D No but for real, it would be very helpful. Implementing and writing that stuff takes some time if you wanna do it properly, this started out as a small side project for my own needs and because nothing similar existed and I didn't care too much about those things. I'll consider investing some time, would be a nice thing to have!

**Comment by anotheri** [comment]
@m1212e back to suggestion i've made some time ago:

> 1. add config option with path to file with custom types (this module(s) should be imported into generated schema files if one of custom types are used in schema);

would it be possible to import my own transformation types and apply to the code generation? e.g. if i have `string | null` in the DB, but i want to apply transformations to integer with default 0 for API.

**Comment by m1212e** [comment]
Not quite sure what exactly you need but you can customize from where the generated code imports the types with the respective config options:

```ts
{
    /**
     * The name of the variable to import the Type from typebox
     */
    typeboxImportVariableName: Type.String({ default: "Type" }),
    /**
     * The name of the dependency to import the Type from typebox
     */
    typeboxImportDependencyName: Type.String({ default: "@sinclair/typebox" }),
}
```

Then you could go ahead and create a custom module similar to this:

```ts
import { Type as NativeType } from "@sinclair/typebox";

const TransformDate = NativeType.Transform(NativeType.Number())
  .Decode((value) => new Date(value))
  .Encode((value) => value.getTime());

export const Type = {
  ...NativeType,
  String: NativeType.String({ additionalProperties: false }),
  Date: TransformDate,
};
```
where you can make your adjustments. Then point prismabox to import from there instead of the default modules.
Does that help?

**Comment by anotheri** [comment]
@m1212e i'll give it a try, at first glance it looks exactly what I need. Thanks for example! 🙏

**Comment by anotheri** [comment]
@m1212e so it works if i need to redefine one of existing default types. But i'd like to be able to define a new type with custom transformation and use it just on a couple of fields in prisma schema and keep default the type mapping for other fields. 

E.g. if i extend Type with new type:

```typescript
import { Type as NativeType } from "@sinclair/typebox";

// e.g. in DB it's stored as string | null but API returns it as integer
const StringifiedInt = NativeType.Transform(NativeType.Integer())
  .Decode((value) => (value === 0 ? null : toString(value)))
  .Encode((value) => parseInt(value || '0', 10));

export const Type = {
  ...NativeType,
  StringifiedInt,
};
```

and then i want to apply this new custom type to a prisma schema field like this:
```
model myModel {
  /// @prismabox.type=StringifiedInt
  myCustomField String? @db.TinyText
}
```

If you think it's good idea, i can open separate issue or reopen this one. Thanks in advance!

**Comment by m1212e** [comment]
I see the point, please open a new issue for this, I'll have a look as soon as I have time
