### ISSUE TITLE
Broken compatibility with Elysia

### ISSUE THREAD

**Issue by SpeedySH** [m1212e/prismabox#26]
With the latest update (1.1.16), a transformer is automatically created for Date (and you can't disable it, it's weird that it's a patch and not a minor).
It tries to import a type that is not exported from elysia by default.

Any suggestions:
1. Add an additional configuration property for importing types.
2. Add an option to disable generation of this.

I can do a PR if needed, it doesn't look complicated :)

**Comment by m1212e** [comment]
Neat side effect: Does not break downwards compatibility this way. So we can continue with the minors and 1.1.17. Just released the update, thanks for the quick heads up!
