### ISSUE TITLE
[BUG] The nullable value keys have to be passed explicilty.

### ISSUE THREAD

**Issue by adarshaacharya** [m1212e/prismabox#7]
If I want to pass the certain optional values, I have to pass it was undefined.

Prisma schema:

```
model Country {
    id        String   @id @default(cuid())
    createdAt DateTime @default(now()) @db.Timestamptz
    updatedAt DateTime @updatedAt @db.Timestamptz

    name        String
    countryCode String
    imageUrl    String?
    code         String?
    @@map("countries")
}

```

Generated output by typebox: 

```ts
export const CountryPlainInput = t.Object(
  {
    name: t.String({ additionalProperties: true }),
    countryCode: t.String({ additionalProperties: true }),
    imageUrl: __nullable__(t.String({ additionalProperties: true })),
    code: __nullable__(t.String({ additionalProperties: true })),
  },
  { additionalProperties: true },
);
```

Inputs: 
for above schema:

Input 1: 
```js
{
name : "USA",
countryCode : "US"
}
```
doesn't work

but

Input 2: 
```js
{
name : "USA",
countryCode : "US",
imageUrl : null,
code : null
}

```

works.

Is there anyway to make the first one (Input 1) work without passing null value explicitly all the time (it will be huge pain in fe)

**Comment by adarshaacharya** [comment]
@m1212e  any update on this

**Comment by m1212e** [comment]
See https://github.com/m1212e/prismabox/releases/tag/1.1.0 and check if this solves your problem. Please also refrain from spam pinging me since I do this in my free time and free of charge.
Also, please close the issue if you see your problem resolved!

**Comment by adarshaacharya** [comment]
@m1212e thanks ! :)
